import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form action="/api/postData" method="post" target="_blank">
          <label htmlFor="first">First name:</label>
          <input type="text" id="first" name="first" />
          <label htmlFor="last">Last name:</label>
          <input type="text" id="last" name="last" />

          {/* <label htmlFor="pswrd">Password:</label>
          <input
            type="password"
            id="pswrd"
            name="pswrd"
            pattern="[a-z0-9]{1,15}"
            title="Password should be digits (0 to 9) or alphabets (a to z)."
          /> */}

          <button type="submit">Post</button>
        </form>

        <form action="/api/getData" method="get" target="_blank">
          <button type="submit">Get</button>
        </form>
      </main>
    </div>
  );
}
